### PR TITLE
Add Configure Method, Add Context and Options Parameters

### PR DESCRIPTION
**Pull request by samcus**
Features:
- Minor Version Bump (Backwards Compatible, No Breaking Changes)
- Ability to Access Axe Configure Method
- Ability to Access Context and Options on the Axe Run Method

### CODE REVIEW

**Comment by nicklemmon** [comment]
@avanslaars - if you have any time to review, this would be a huge addition! Only if you have time, obviously.

Thanks again for your work on this project.

**Comment by avanslaars** [comment]
@samcus, Sorry for the delay. I was traveling for work and didn't have any time to look at this. I think this is a great addition. Thank you so much for the contribution! I'll get it merged in and published to npm.

**Comment by avanslaars** [comment]
@all-contributors please add @samcus for code and doc

**Comment by avanslaars** [comment]
@all-contributors please add @samcus for code and doc

**Pull request merged**
